/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author BigBlackBug
 */
public class TeamJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TeamJPanel
     */
    public TeamJPanel() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player1Panel = new main.PlayerEntryPanel();
        player2Panel = new main.PlayerEntryPanel();
        player3Panel = new main.PlayerEntryPanel();
        player4Panel = new main.PlayerEntryPanel();
        player5Panel = new main.PlayerEntryPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addComponent(player2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(player3Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(player5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(player4Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(player1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player4Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player5Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.PlayerEntryPanel player1Panel;
    private main.PlayerEntryPanel player2Panel;
    private main.PlayerEntryPanel player3Panel;
    private main.PlayerEntryPanel player4Panel;
    private main.PlayerEntryPanel player5Panel;
    // End of variables declaration//GEN-END:variables

    public PlayerEntryPanel getPlayer1Panel() {
        return player1Panel;
    }
    
    /**
     * @return the player2Panel
     */
    public main.PlayerEntryPanel getPlayer2Panel() {
        return player2Panel;
    }

    /**
     * @return the player3Panel
     */
    public main.PlayerEntryPanel getPlayer3Panel() {
        return player3Panel;
    }

    /**
     * @return the player4Panel
     */
    public main.PlayerEntryPanel getPlayer4Panel() {
        return player4Panel;
    }

    /**
     * @return the player5Panel
     */
    public main.PlayerEntryPanel getPlayer5Panel() {
        return player5Panel;
    }
}
