/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qbix.pm.client.view;

import org.qbix.pm.client.controller.interfaces.PlayerEntryPanelController;
import org.qbix.pm.client.controller.interfaces.SessionSettingsPanelController;
import org.qbix.pm.client.misc.PlaymoreSessionStatus;
import org.qbix.pm.client.view.interfaces.PMTeamView;

/**
 *
 * @author BigBlackBug
 */
public class MainPanel extends javax.swing.JPanel implements PMTeamView {

    /**
     * Creates new form NewJPanel
     */
    public MainPanel() {
        initComponents();
    }
    
	@Override
	public PlayerEntryPanelController getPlayerEntryPanelController(
			Long accountID) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public SessionSettingsPanelController getSessionSettingsController() {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public void setSessionStatus(PlaymoreSessionStatus status) {
		// TODO Auto-generated method stub
		
	}
	@Override
	public void showView() {
		// TODO Auto-generated method stub
	}

	@Override
	public void hideView() {
		// TODO Auto-generated method stub
	}
	
	
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        team2JPanel = new org.qbix.pm.client.view.TeamJPanel();
        team1JPanel = new org.qbix.pm.client.view.TeamJPanel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("host confirm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(team1JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(team2JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(team2JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(team1JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private org.qbix.pm.client.view.PlayerEntryPanel playerEntryPanel10;
    private org.qbix.pm.client.view.PlayerEntryPanel playerEntryPanel11;
    private org.qbix.pm.client.view.PlayerEntryPanel playerEntryPanel7;
    private org.qbix.pm.client.view.PlayerEntryPanel playerEntryPanel8;
    private org.qbix.pm.client.view.PlayerEntryPanel playerEntryPanel9;
    private org.qbix.pm.client.view.TeamJPanel team1JPanel;
    private org.qbix.pm.client.view.TeamJPanel team2JPanel;
    // End of variables declaration//GEN-END:variables

}
