/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qbix.pm.client.view;

import org.qbix.pm.client.misc.PlaymoreSessionStatus;
import org.qbix.pm.client.model.GameDTO;
import org.qbix.pm.client.notifications.ParticipantsReturnInfo;
import org.qbix.pm.client.view.interfaces.PMMainView;
import org.qbix.pm.client.view.interfaces.PlayerEntryPanelView;
import org.qbix.pm.client.view.interfaces.SessionSettingsPanelView;

/**
 *
 * @author BigBlackBug
 */
public class MainFrame extends javax.swing.JFrame implements PMMainView{

	public MainFrame() {
        initComponents();
    }
    
    @Override
	public void showView() {
		setVisible(true);
		
	}

	@Override
	public void hideView() {
		setVisible(true);		
	}

	@Override
	public PlayerEntryPanelView getPlayerEntryPanelView(Long accountID) {
		PlayerEntryPanelView view1 = teamJPanel1
				.getPlayerEntryPanelView(accountID);
		PlayerEntryPanelView view2 = teamJPanel2
				.getPlayerEntryPanelView(accountID);
		if (view1 == null) {
			if (view2 == null) {
				throw new RuntimeException();
			} else {
				return view2;
			}
		} else {
			return view1;
		}
	}

	@Override
	public SessionSettingsPanelView getSessionSettingsView() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setSessionStatus(PlaymoreSessionStatus status) {
		// TODO Auto-generated method stub
		
	}
	
	@Override
	public void fill(GameDTO gameDTO, ParticipantsReturnInfo info) {
		teamJPanel1.fill(gameDTO.getTeamOne(), info.getTeamOne());
		teamJPanel2.fill(gameDTO.getTeamTwo(), info.getTeamTwo());
	}
	
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamJPanel1 = new org.qbix.pm.client.view.TeamJPanel();
        teamJPanel2 = new org.qbix.pm.client.view.TeamJPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teamJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teamJPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(teamJPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private org.qbix.pm.client.view.TeamJPanel teamJPanel1;
    private org.qbix.pm.client.view.TeamJPanel teamJPanel2;
    // End of variables declaration//GEN-END:variables
	
}
