/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qbix.pm.client.view;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.qbix.collection.CollectionUtils;
import org.qbix.collection.predicates.Predicate;
import org.qbix.pm.client.model.lol.PlayerParticipant;
import org.qbix.pm.client.model.pm.GameDTO;
import org.qbix.pm.client.model.pm.PlayerEntryDTO;
import org.qbix.pm.client.view.interfaces.PlayerEntryPanelView;
import org.qbix.pm.client.view.interfaces.TeamPanelView;

/**
 *
 * @author BigBlackBug
 */
public class TeamJPanel extends javax.swing.JPanel implements TeamPanelView{
	
	private static final int MAX_PLAYERS = 5;
	
	private Map<Long, PlayerEntryPanelView> map;
	private final List<PlayerEntryPanelView> views;
    /**
     * Creates new form TeamJPanel
     */
	public TeamJPanel() {
		initComponents();
		map = new HashMap<>();
		views = new ArrayList<>();
		views.add(player1Panel);
		views.add(player2Panel);
		views.add(player3Panel);
		views.add(player4Panel);
		views.add(player5Panel);
	}

	@Override
	public void fill(List<PlayerParticipant> players,
			GameDTO gameDTO) {
		for (int i = 0; i < MAX_PLAYERS; i++) {
			PlayerEntryPanelView view = views.get(i);
			PlayerParticipant participant = players.get(i);
			PlayerEntryDTO entry = getPlayerEntry(gameDTO.getPlayerEntries(),
					participant.getAccountId());
			fillOne(view, participant, entry);
		}
	}

	private PlayerEntryDTO getPlayerEntry(List<PlayerEntryDTO> playerEntries,
			final Long lolAccountId) {
		return CollectionUtils.filterEntities(playerEntries,
			new Predicate<PlayerEntryDTO>() {
				@Override
				public boolean isSatisfiedBy(PlayerEntryDTO entity) {
					return entity.getLolAccountId() == lolAccountId;
				}
			}).toEntity();
	}

	private void fillOne(PlayerEntryPanelView view, PlayerParticipant pp,
			PlayerEntryDTO entry) {
		view.fill(pp, entry);
		map.put(entry.getAccountId(), view);
	}
	
	
    @Override
	public PlayerEntryPanelView getPlayerEntryPanelView(
			Long pmAccountID) {
		return map.get(pmAccountID);
	}

	@Override
	public PlayerEntryPanelView getPlayer1Panel() {
		return player1Panel;
	}


	@Override
	public PlayerEntryPanelView getPlayer2Panel() {
		return player2Panel;
	}


	@Override
	public PlayerEntryPanelView getPlayer3Panel() {
		return player3Panel;
	}


	@Override
	public PlayerEntryPanelView getPlayer4Panel() {
		return player4Panel;
	}


	@Override
	public PlayerEntryPanelView getPlayer5Panel() {
		return player5Panel;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player1Panel = new org.qbix.pm.client.view.PlayerEntryPanel();
        player2Panel = new org.qbix.pm.client.view.PlayerEntryPanel();
        player3Panel = new org.qbix.pm.client.view.PlayerEntryPanel();
        player4Panel = new org.qbix.pm.client.view.PlayerEntryPanel();
        player5Panel = new org.qbix.pm.client.view.PlayerEntryPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(player4Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player5Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(player1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player4Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player5Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.qbix.pm.client.view.PlayerEntryPanel player1Panel;
    private org.qbix.pm.client.view.PlayerEntryPanel player2Panel;
    private org.qbix.pm.client.view.PlayerEntryPanel player3Panel;
    private org.qbix.pm.client.view.PlayerEntryPanel player4Panel;
    private org.qbix.pm.client.view.PlayerEntryPanel player5Panel;
    // End of variables declaration//GEN-END:variables

}